### ISSUE TITLE
Command wrong in the README

### ISSUE THREAD

**Issue by mattkosack** [mmorykan/YoutubeDownloader#2]
The `pyinstaller --onefile --windowed --icon=resource/icon.ico --add-binary=ffmpeg_windows/bin/*:. app/app.py` needs to be adjusted for windows. 

pyinstaller --onefile --windowed --icon=resource\icon.ico --add-binary=ffmpeg_windows\bin\*;. app\app.py

**Comment by mmorykan** [comment]
Thank you for raising this issue. You left out a backslash between 'bin' and '*'. But the issue has now been fixed

**Comment by mmorykan** [comment]
README has been updated for Windows capability
