### ISSUE TITLE
Cannot bundle application

### ISSUE THREAD

**Issue by mattkosack** [mmorykan/YoutubeDownloader#3]
I was unable to bundle this and had an error of `no matches found: --add-binary=ffmpeg_mac/bin/*:.` when using your command for pyinstaller

**Comment by mattkosack** [comment]
Solved the issue `pyinstaller --onefile --windowed --icon=resource/icon.icns --add-binary=ffmpeg_mac/bin/\*:. -n "Youtube Downloader" --clean app/app.py`

zsh would not recognize the `*`, fixed by escaping with `\`

**Comment by mmorykan** [comment]
Thank you for the fix!
